AllCops:
  DisplayCopNames: true
  Exclude:
    - 'app/models/concerns/simulation_inputs_concern.rb'
    - 'app/controllers/door_controller.rb'
    - 'test/**/*'
    - 'bin/*'
    - 'db/schema.rb'
# Rails:
#   Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 1500
Metrics/ModuleLength:
  Enabled: false
Metrics/MethodLength:
  Max: 200
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Metrics/PerceivedComplexity:
  Max: 200
Metrics/ClassLength:
  Max: 300
# Style/BracesAroundHashParameters:
#   Enabled: false
Style/RedundantSelf:
  Enabled: false
Layout/SpaceAfterComma:
  Enabled: false
# Style/SymbolProc:
#   Enabled: false
Style/HashSyntax:
  Enabled: false
# Rails/HasManyOrHasOneDependent:
#   Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/RedundantParentheses:
  Enabled: false
Style/WordArray:
  Enabled: false
Layout/LeadingCommentSpace:
  Enabled: false
Style/RedundantReturn:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Next:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/SpaceAfterColon:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Layout/EmptyLinesAroundMethodBody:
  Enabled: false
Style/RedundantInterpolation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 200
Style/ConditionalAssignment:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
# Performance/RangeInclude:
#   Enabled: false
Style/RescueStandardError:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/AbcSize:
  Max: 400
Naming/VariableName:
  Enabled: false
Style/CommentedKeyword:
  Enabled: false
Style/Lambda:
  Enabled: false  
Naming/MethodName:
  Enabled: false
Lint/ImplicitStringConcatenation:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/IdenticalConditionalBranches:
  Enabled: false
# Rails/Presence:
#   Enabled: false
Style/Documentation:
  Enabled: false    
Style/StringLiteralsInInterpolation:
  Enabled: false
Layout/SpaceInsideBlockBraces:
  Enabled: false  
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Lint/UselessAssignment:
  Enabled: false
Style/SelfAssignment:
  Enabled: false
Layout/ClosingParenthesisIndentation:
  Enabled: false        
Style/NumericPredicate:
  Enabled: false
Naming/PredicateName:
  Enabled: false  
Metrics/BlockLength:
  Max: 600
Style/RescueModifier:
  Enabled: false
Style/SpecialGlobalVars:
  Enabled: false
# Layout/LineLength:
#   Max: 400
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Lint/SafeNavigationChain:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
