clone:
  depth: full

pipelines:
  branches:
    master:
      - step:
          name: SonarQube analysis
          image: sonarsource/sonar-scanner-cli:latest
          caches:
            - sonar
          script:
            - pipe: sonarsource/sonarcloud-scan:1.4.0
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

  pull-requests:
    '**':
      - step:
          name: SonarQube analysis
          image: sonarsource/sonar-scanner-cli:latest
          caches:
            - sonar
          script:
            - pipe: sonarsource/sonarcloud-scan:1.4.0
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

definitions:
  caches:
    sonar: /opt/sonar-scanner/.sonar
