zero: 0
one: 1
two: 2
third: 3
limit_appointment_recurrence: 30
limit_service_address_type: 250
service_address: 'service_address'
office: 2
all_days: [0,1,2,3,4,5,6]
days_name: ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
daily: 'daily'
weekly: 'weekly'
monthly: 'monthly'
yearly: 'yearly'
days:
  sunday: 6
  monday: 0
  tuesday: 1
  wednesday: 2
  thursday: 3
  friday: 4
  saturday: 5
roles:
  super_admin: super_admin
  ccc: client_care_coordinator
  cd: Clinical Director
  ed: executive_director
