default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: aba_centre_be_dev

test:
  <<: *default
  database: aba_centre_be_test

staging:
  <<: *default
  database: <%= Rails.application.credentials.dig(:database, :db_name) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>

production:
  <<: *default
  host: <%= Rails.application.credentials.dig(:database, :host) %>
  database: <%= Rails.application.credentials.dig(:database, :db_name) %>
  username: <%= Rails.application.credentials.dig(:database, :username) %>
  password: <%= Rails.application.credentials.dig(:database, :password) %>
