default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

development:
  <<: *default
  database: aba_centre_be_dev

test:
  <<: *default
  database: aba_centre_be_test
