update_user_status_worker:
  cron: '1 0 * * *'
  class: "UpdateUserStatusWorker"
  queue: UpdateUserStatus

render_service_worker:
  cron: '1 0 * * *'
  class: "RenderAppointmentsWorker"
  queue: RenderAppointments

sync_soap_notes_with_catalyst_two_months_worker_at_10_pm:
  cron: '0 22 * * *'
  class: "SyncWithCatalystTwoMonthsWorker"
  queue: SyncWithCatalystTwoMonths

sync_soap_notes_with_catalyst_every_1_hours:
  cron: '0 */1 * * *'
  class: "SyncWithCatalystWorker"
  queue: SyncWithCatalyst

sync_staff_and_client_with_catalyst_at_10_am:
  cron: '0 10 * * *'
  class: "SyncStaffAndClientWithCatalystWorker"
  queue: SyncStaffAndClientWithCatalyst

sync_staff_and_client_with_catalyst_at_7_pm:
  cron: '0 19 * * *'
  class: "SyncStaffAndClientWithCatalystWorker"
  queue: SyncStaffAndClientWithCatalyst

destroy_unassigned_past_appointments:
  cron: '5 0 * * *'
  class: "DestroyUnassignedAppointmentsWorker"
  queue: DestroyUnassignedAppointments

destroy_unused_expired_early_authorizations:
  cron: '0 1 * * *'
  class: "DestroyUnusedExpiredEarlyAuthorizationsWorker"
  queue: DestroyUnusedExpiredEarlyAuthorizations

process_claim_statuses_every_monday_5am:
  cron: '0 5 * * 1'
  class: "AvailityProcessClaimsWorker"
  queue: AvailityProcessClaims
