update_user_status_worker:
  cron: '1 0 * * *'
  class: "UpdateUserStatusWorker"

render_service_worker:
  cron: '1 0 * * *'
  class: "RenderAppointmentsWorker"

sync_soap_notes_with_catalyst_one_month_worker_at_10_pm:
  cron: '0 22 * * *'
  class: "SyncWithCatalystOneMonthWorker"

sync_soap_notes_with_catalyst_at_11_am:
  cron: '0 11 * * *'
  class: "SyncWithCatalystWorker"

sync_soap_notes_with_catalyst_at_3_pm:
  cron: '0 15 * * *'
  class: "SyncWithCatalystWorker"

sync_soap_notes_with_catalyst_at_9_pm:
  cron: '0 21 * * *'
  class: "SyncWithCatalystWorker"

sync_staff_and_client_with_catalyst_at_10_am:
  cron: '0 10 * * *'
  class: "SyncStaffAndClientWithCatalystWorker"

sync_staff_and_client_with_catalyst_at_7_pm:
  cron: '0 19 * * *'
  class: "SyncStaffAndClientWithCatalystWorker"

s3_sync_at_3_am:
  cron: '0 3 * * *'
  class: "S3SyncWorker"